### ISSUE TITLE
Account on squeak.slack.com

### ISSUE THREAD

**Issue by eikeon** [ccrraaiigg/context#23]
I'd be interested in the discussions at http://squeak.slack.com but don't see a way to request an account.

**Comment by ccrraaiigg** [comment]
You just did, invite sent. :)

**Comment by npe9** [comment]
Same here :)

**Comment by ccrraaiigg** [comment]
Cool! https://join.slack.com/t/squeak/shared_invite/enQtNDg5NzIxNDkzMjUzLWQ1YTVmOTNiZThmYTdiN2U3MDMzMWRlOTE1NDg2NGNlNjcxNTE2MTA5NGE5MDA1MWE5MjJiMGFmYmM1MDM2MTU (expires in seven days)

**Comment by npe9** [comment]
Thanks!
