### ISSUE TITLE
Are any ports of this technology exists in the form of a tiny engine for Linux?

### ISSUE THREAD

**Issue by ponyatov** [ccrraaiigg/context#26]
Are any ports of minimized object engine exists in form of C-written VM can be built for embedded MIPS-bases systems? (I mean Buidlroot/OpenWrt systems and maybe STM32F7 devboards).

Looking inside of this core project, it looks like I need full-sized JS engine unable to run on my RT5350 devices.

**Comment by ccrraaiigg** [comment]
This should be doable; I would start with the C-based Squeak VM at http://opensmalltalk.org/.
